version: '3.8'

services:
  frontend:
    image: ${CI_REGISTRY_IMAGE}/frontend:${CI_COMMIT_SHA}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${WORKER1_HOSTNAME}
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - swarm-net
    environment:
      - PORT=4000
      - REACT_APP_API_URL=/api

  backend:
    image: ${CI_REGISTRY_IMAGE}/backend:${CI_COMMIT_SHA}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == ${WORKER2_HOSTNAME}
      restart_policy:
        condition: on-failure
        max_attempts: 3
    networks:
      - swarm-net
    environment:
      - PORT=5000
      - MONGODB_URI=${MONGODB_URI}
      # Add any other environment variables your backend needs

  nginx:
    image: ${CI_REGISTRY_IMAGE}/nginx:${CI_COMMIT_SHA}
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure
    ports:
      - "80:80"
    networks:
      - swarm-net
    depends_on:
      - frontend
      - backend

networks:
  swarm-net:
    external: true
